module.exports = {
    alps: require('./alps'),
    bat: require('./bat'),
    button: require('./button'),
    choc: require('./choc'),
    choc_led: require('./choc_led'),
    choc_stl: require('./choc_stl'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
    diode_alt: require('./diode_alt'),
    jstph: require('./jstph'),
    jumper: require('./jumper'),
    mx: require('./mx'),
    niceview: require('./niceview'),
    oled: require('./oled'),
    omron: require('./omron'),
    pad: require('./pad'),
    pcm12: require('./pcm12'),
    promicro: require('./promicro'),
    promicro_pretty: require('./promicro_pretty'),
    rgb: require('./rgb'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
    slider: require('./slider'),
    trrs: require('./trrs'),
    via: require('./via'),
}
